export type Category = {
  name: string;
  description: string;
  popular: string[];
  services: string[] | ServiceGroup[];
};

export type ServiceGroup = {
  groupName: string;
  image: string;
  items: string[];
};

export const categoriesData: Category[] = [
  {
    name: "Bands",
    description:
      "From rock to jazz, find the perfect band to create an unforgettable atmosphere for your event.",
    popular: [
      "Cover Band",
      "Variety Band",
      "Jazz Band",
      "Rock Band",
      "Country Band",
      "80s Band",
    ],
    services: [
      "60s Band",
      "70s Band",
      "80s Band",
      "90s Band",
      "Acoustic Band",
      "Americana Band",
      "Beach Band",
      "Big Band",
      "Bluegrass Band",
      "Blues Band",
      "Brass Band",
      "Cajun Band",
      "Caribbean Band",
      "Celtic Band",
      "Christian Rock Band",
      "Classic Rock Band",
      "Country Band",
      "Cover Band",
      "Dance Band",
      "Disco Band",
      "Dixieland Band",
      "Flamenco Band",
      "Folk Band",
      "French Band",
      "Funk Band",
      "German Band",
      "Hawaiian Band",
      "Indie Rock Band",
      "Irish Band",
      "Jam Band",
      "Jazz Band",
      "Karaoke Band",
      "Latin Band",
      "Marching Band",
      "Mariachi Band",
      "Merengue Band",
      "Motown Band",
      "Oldies Band",
      "Polka Band",
      "Pop Band",
      "R&B Band",
      "Reggae Band",
      "Rock Band",
      "Salsa Band",
      "Soul Band",
      "Southern Rock Band",
      "Steel Drum Band",
      "Swing Band",
      "Top 40 Band",
      "Variety Band",
      "World Music Band",
    ],
  },
  {
    name: "Solo Musicians",
    description:
      "Add a touch of elegance or a lively vibe with our talented solo musicians, from classical guitarists to pop singers.",
    popular: [
      "Acoustic Guitar",
      "Piano",
      "Singer Guitarist",
      "Violin",
      "Saxophone",
      "Harp",
    ],
    services: [
      "Accordion",
      "Acoustic Guitar",
      "Ambient Guitar",
      "Ambient Piano",
      "Bagpipes",
      "Beach Music Singer",
      "Blues Guitar",
      "Broadway Singer",
      "Cello",
      "Celtic Bagpipes",
      "Children's Music Singer",
      "Classic Rock Guitar",
      "Classical Guitar",
      "Classical Piano",
      "Classical Singer",
      "Country Singer",
      "Fiddler",
      "Flamenco Acoustic Guitar",
      "Flamenco Guitar",
      "Flute",
      "Folk Singer",
      "Gospel Singer",
      "Guitar",
      "Harp",
      "Hawaiian Guitar",
      "Italian Singer",
      "Jazz Guitar",
      "Jazz Keyboards",
      "Jazz Piano",
      "Jazz Singer",
      "Jazz Violin",
      "Keyboards",
      "Latin Guitar",
      "Motown Singer",
      "One Man Band",
      "Opera Singer",
      "Piano",
      "Pop Piano",
      "Pop Singer",
      "R&B Singer",
      "Saxophone",
      "Singer",
      "Singer Guitarist",
      "Singing Pianist",
      "Soul Singer",
      "Steel Drum",
      "Trumpet",
      "Ukulele",
      "Variety Singer",
      "Violin",
    ],
  },
  {
    name: "Ensembles",
    description: "Discover the perfect harmony for your event.",
    popular: [
      "String Quartet",
      "Jazz Trio",
      "Acoustic Duo",
      "Barbershop Quartet",
      "Dueling Pianos",
      "Classical Trio",
    ],
    services: [
      "A Cappella Group",
      "Acoustic Duo",
      "Acoustic Trio",
      "Americana Duo",
      "Barbershop Quartet",
      "Celtic Duo",
      "Celtic Trio",
      "Chamber Music Duo",
      "Chamber Music Trio",
      "Choir",
      "Christmas Carolers",
      "Classic Rock Duo",
      "Classical Duo",
      "Classical Quartet",
      "Classical Trio",
      "Country Duo",
      "Dueling Pianos",
      "Flamenco Duo",
      "Irish Duo",
      "Jazz Duo",
      "Jazz Ensemble",
      "Jazz Quartet",
      "Jazz Trio",
      "Latin Duo",
      "Pop Duo",
      "Pop Trio",
      "String Quartet",
      "Variety Duo",
      "Variety Trio",
      "Woodwind Ensemble",
    ],
  },
  {
    name: "DJs",
    description:
      "Keep the party going with our professional DJs who know how to read the crowd and play the right music at the right time.",
    popular: ["DJ", "Karaoke DJ", "Latin DJ"],
    services: ["DJ", "Karaoke DJ", "Latin DJ"],
  },
  {
    name: "Variety Acts",
    description:
      "Surprise and delight your guests with unique variety acts, from magicians and comedians to fire dancers and caricaturists.",
    popular: [
      "Magician",
      "Face Painting",
      "Caricaturist",
      "Belly Dancer",
      "Fire Dancer",
      "Hypnotist",
    ],
    services: [
      "Acrobat",
      "Airbrush T-Shirts",
      "Astrologer",
      "Balloon Twister",
      "Belly Dancer",
      "Body Painting",
      "Bollywood Dancer",
      "Cabaret Dancer",
      "Caricaturist",
      "Circus Act",
      "Clown",
      "Comedy Hypnotist",
      "Comedy Magician",
      "Contortionist",
      "Costumed Character",
      "Dance Group",
      "Dancer",
      "Easter Bunny",
      "Face Painting",
      "Fire Dancer",
      "Fire Eater",
      "Flamenco Dancer",
      "Fortune Teller",
      "Hawaiian Dancer",
      "Henna Artist",
      "Hip Hop Dancer",
      "Hula Dancer",
      "Human Statue",
      "Hypnotist",
      "Illusionist",
      "Interactive Game Show",
      "Irish Dancer",
      "Juggler",
      "Latin Dancer",
      "Live Painter",
      "Magician",
      "Mentalist",
      "Mermaid Entertainment",
      "Mime",
      "Murder Mystery Entertainment",
      "Origami Artist",
      "Palm Reader",
      "Party Robot",
      "Polynesian Dancer",
      "Princess Party",
      "Psychic",
      "Puppet Shows",
      "Samba Dancer",
      "Santa Claus",
      "Silhouette Artist",
      "Singing Telegram",
      "Square Dance Caller",
      "Stilt Walker",
      "Storyteller",
      "Tarot Card Reader",
      "Temporary Tattoos",
      "Ventriloquist",
    ],
  },
  {
    name: "Speakers",
    description:
      "Inspire, motivate, or entertain your audience with our experienced speakers, including keynote speakers, motivational speakers, and emcees.",
    popular: [
      "Motivational Speaker",
      "Keynote Speaker",
      "Emcee",
      "Public Speaker",
      "Wedding Officiant",
      "Auctioneer",
    ],
    services: [
      "Auctioneer",
      "Corporate Speaker",
      "Educational Speaker",
      "Emcee",
      "Keynote Speaker",
      "Motivational Speaker",
      "Public Speaker",
      "Spoken Word Artist",
      "Wedding Minister",
      "Wedding Officiant",
    ],
  },
  {
    name: "Comedians",
    description:
      "Bring laughter to your event with our hilarious comedians, perfect for corporate events, private parties, and clubs.",
    popular: ["Comedian", "Stand Up Comedian", "Clean Comedian"],
    services: ["Clean Comedian", "Comedian", "Stand Up Comedian"],
  },
  {
    name: "Party Rentals",
    description:
      "Everything you need for your next party, from bounce houses and photo booths to tents and carnival games.",
    popular: [
      "Photo Booth Rental",
      "Bounce House",
      "Party Tent Rentals",
      "Casino Games",
      "Dunk Tank Rental",
      "Carnival Games",
    ],
    services: [
      "Animals For Parties",
      "Bounce House",
      "Bubble Party Rental",
      "Carnival Games",
      "Carnival Rides",
      "Casino Games",
      "Dove Releases",
      "Dunk Tank Rental",
      "Laser Tag Party Rental",
      "Outdoor Movie Screen Rental",
      "Party Inflatables",
      "Party Tent Rentals",
      "Petting Zoo",
      "Photo Booth Rental",
      "Pony Rides",
      "Reptile Show",
      "Video Game Party Rental",
    ],
  },
  {
    name: "Photographers / Videographers",
    description:
      "Capture the memories of your special event with our professional photographers and videographers.",
    popular: ["Photographer", "Videographer"],
    services: ["Photographer", "Videographer"],
  },
  {
    name: "Event Staffing",
    description:
      "Ensure your event runs smoothly with our professional event staff, including bartenders, caterers, and servers.",
    popular: [
      "Bartender",
      "Caterer",
      "Food Trucks",
      "Cigar Roller",
      "Sommelier",
      "Chocolate Fountains",
    ],
    services: [
      "Bartender",
      "Caterer",
      "Chocolate Fountains",
      "Cigar Roller",
      "Coffee Cart",
      "Food Trucks",
      "Sommelier",
    ],
  },
  {
    name: "Personal Style",
    description:
      "Look and feel your best for your event with our personal stylists, including hair stylists and makeup artists.",
    popular: ["Makeup Artist", "Hair Stylist"],
    services: ["Hair Stylist", "Makeup Artist"],
  },
  {
    name: "Event Planning",
    description:
      "Let us handle the details. Our event planners will help you create a seamless and memorable event from start to finish.",
    popular: ["Event Planner", "Florist", "Balloon Decor"],
    services: ["Balloon Decor", "Event Planner", "Florist"],
  },
];

// Re-exporting all services/categories as a flat list for components that need it
export const allCategories = categoriesData.map((cat) => cat.name);

export const allServices = categoriesData.flatMap((cat) => {
  const [first] = cat.services;
  if (typeof first === "string" || first === undefined) {
    return cat.services as string[];
  }
  return (cat.services as ServiceGroup[]).flatMap((g) => g.items);
});

// Combined flat list (categories first), de-duplicated while preserving first-occurrence order
export const allCategoriesAndServices = Array.from(
  new Set([...allCategories, ...allServices]),
);
export const popularSearches = [
  "DJs for wedding",
  "event photographer",
  "stand-up comedian",
  "motivational speaker",
];
