export const categoriesData = [
  {
    name: "Bands",
    services: [
      "60s Band",
      "70s Band",
      "80s Band",
      "90s Band",
      "Acoustic Band",
      "Americana Band",
      "Beach Band",
      "Big Band",
      "Bluegrass Band",
      "Blues Band",
      "Brass Band",
      "Cajun Band",
      "Caribbean Band",
      "Celtic Band",
      "Christian Rock Band",
      "Classic Rock Band",
      "Country Band",
      "Cover Band",
      "Dance Band",
      "Disco Band",
      "Dixieland Band",
      "Flamenco Band",
      "Folk Band",
      "French Band",
      "Funk Band",
      "German Band",
      "Hawaiian Band",
      "Indie Rock Band",
      "Irish Band",
      "Jam Band",
      "Jazz Band",
      "Karaoke Band",
      "Latin Band",
      "Marching Band",
      "Mariachi Band",
      "Merengue Band",
      "Motown Band",
      "Oldies Band",
      "Polka Band",
      "Pop Band",
      "R&B Band",
      "Reggae Band",
      "Rock Band",
      "Salsa Band",
      "Soul Band",
      "Southern Rock Band",
      "Steel Drum Band",
      "Swing Band",
      "Top 40 Band",
      "Variety Band",
      "World Music Band",
    ],
  },
  {
    name: "Solo Musicians",
    services: [
      "Accordion",
      "Acoustic Guitar",
      "Ambient Guitar",
      "Ambient Piano",
      "Bagpipes",
      "Beach Music Singer",
      "Blues Guitar",
      "Broadway Singer",
      "Cello",
      "Celtic Bagpipes",
      "Children's Music Singer",
      "Classic Rock Guitar",
      "Classical Guitar",
      "Classical Piano",
      "Classical Singer",
      "Country Singer",
      "Fiddler",
      "Flamenco Acoustic Guitar",
      "Flamenco Guitar",
      "Flute",
      "Folk Singer",
      "Gospel Singer",
      "Guitar",
      "Harp",
      "Hawaiian Guitar",
      "Italian Singer",
      "Jazz Guitar",
      "Jazz Keyboards",
      "Jazz Piano",
      "Jazz Singer",
      "Jazz Violin",
      "Keyboards",
      "Latin Guitar",
      "Motown Singer",
      "One Man Band",
      "Opera Singer",
      "Piano",
      "Pop Piano",
      "Pop Singer",
      "R&B Singer",
      "Saxophone",
      "Singer",
      "Singer Guitarist",
      "Singing Pianist",
      "Soul Singer",
      "Steel Drum",
      "Trumpet",
      "Ukulele",
      "Variety Singer",
      "Violin",
    ],
  },
  {
    name: "Ensembles",
    services: [
      "A Cappella Group",
      "Acoustic Duo",
      "Acoustic Trio",
      "Americana Duo",
      "Barbershop Quartet",
      "Celtic Duo",
      "Celtic Trio",
      "Chamber Music Duo",
      "Chamber Music Trio",
      "Choir",
      "Christmas Carolers",
      "Classic Rock Duo",
      "Classical Duo",
      "Classical Quartet",
      "Classical Trio",
      "Country Duo",
      "Dueling Pianos",
      "Flamenco Duo",
      "Irish Duo",
      "Jazz Duo",
      "Jazz Ensemble",
      "Jazz Quartet",
      "Jazz Trio",
      "Latin Duo",
      "Pop Duo",
      "Pop Trio",
      "String Quartet",
      "Variety Duo",
      "Variety Trio",
      "Woodwind Ensemble",
    ],
  },
  {
    name: "DJs",
    services: ["DJ", "Karaoke DJ", "Latin DJ"],
  },
  {
    name: "Variety Acts",
    services: [
      "Acrobat",
      "Airbrush T-Shirts",
      "Astrologer",
      "Balloon Twister",
      "Belly Dancer",
      "Body Painting",
      "Bollywood Dancer",
      "Cabaret Dancer",
      "Caricaturist",
      "Circus Act",
      "Clown",
      "Comedy Hypnotist",
      "Comedy Magician",
      "Contortionist",
      "Costumed Character",
      "Dance Group",
      "Dancer",
      "Easter Bunny",
      "Face Painting",
      "Fire Dancer",
      "Fire Eater",
      "Flamenco Dancer",
      "Fortune Teller",
      "Hawaiian Dancer",
      "Henna Artist",
      "Hip Hop Dancer",
      "Hula Dancer",
      "Human Statue",
      "Hypnotist",
      "Illusionist",
      "Interactive Game Show",
      "Irish Dancer",
      "Juggler",
      "Latin Dancer",
      "Live Painter",
      "Magician",
      "Mentalist",
      "Mermaid Entertainment",
      "Mime",
      "Murder Mystery Entertainment",
      "Origami Artist",
      "Palm Reader",
      "Party Robot",
      "Polynesian Dancer",
      "Princess Party",
      "Psychic",
      "Puppet Shows",
      "Samba Dancer",
      "Santa Claus",
      "Silhouette Artist",
      "Singing Telegram",
      "Square Dance Caller",
      "Stilt Walker",
      "Storyteller",
      "Tarot Card Reader",
      "Temporary Tattoos",
      "Ventriloquist",
    ],
  },
  {
    name: "Speakers",
    services: [
      "Auctioneer",
      "Corporate Speaker",
      "Educational Speaker",
      "Emcee",
      "Keynote Speaker",
      "Motivational Speaker",
      "Public Speaker",
      "Spoken Word Artist",
      "Wedding Minister",
      "Wedding Officiant",
    ],
  },
  {
    name: "Comedians",
    services: ["Clean Comedian", "Comedian", "Stand Up Comedian"],
  },
  {
    name: "Party Rentals",
    services: [
      "Animals For Parties",
      "Bounce House",
      "Bubble Party Rental",
      "Carnival Games",
      "Carnival Rides",
      "Casino Games",
      "Dove Releases",
      "Dunk Tank Rental",
      "Laser Tag Party Rental",
      "Outdoor Movie Screen Rental",
      "Party Inflatables",
      "Party Tent Rentals",
      "Petting Zoo",
      "Photo Booth Rental",
      "Pony Rides",
      "Reptile Show",
      "Video Game Party Rental",
    ],
  },
  {
    name: "Photographers / Videographers",
    services: ["Photographer", "Videographer"],
  },
  {
    name: "Event Staffing",
    services: [
      "Bartender",
      "Caterer",
      "Chocolate Fountains",
      "Cigar Roller",
      "Coffee Cart",
      "Food Trucks",
      "Sommelier",
    ],
  },
  {
    name: "Personal Style",
    services: ["Hair Stylist", "Makeup Artist"],
  },
  {
    name: "Event Planning",
    services: ["Balloon Decor", "Event Planner", "Florist"],
  },
];

// Re-exporting all services/categories as a flat list for components that need it
export const allCategories = categoriesData.map((cat) => cat.name);

export const allServices = categoriesData.flatMap((cat) => cat.services);

// Combined flat list (categories first), de-duplicated while preserving first-occurrence order
export const allCategoriesAndServices = Array.from(
	new Set([...allCategories, ...allServices])
);
export const popularSearches = [
  "DJs for wedding",
  "event photographer",
  "stand-up comedian",
  "motivational speaker",
];
